### ISSUE TITLE
Connect/disconnect/reconnect events

### ISSUE THREAD

**Issue by ThePooN** [d-fischer/twitch-pubsub-client#2]
## Feature Request

No event is currently emitted on the status of the PubSubClient. I would appreciate being able to log the status of the PubSubClient.

**Comment by d-fischer** [comment]
I added `onConnect` and `onDisconnect` events. I did not add a reconnect event. Instead, the `onDisconnect` event will pass a parameter called `isError` which shows whether the disconnect was intentional or not. If the disconnect was not intentional, the client will always reconnect.
